### PR TITLE
YSU CPF: INTENTs, inits; errmsg etc; add metadata file; 

### PR DESCRIPTION
**Pull request by davegill**
1. The routine calling the YSU scheme has access to the flag_qc
and flag_qi logicals. The flag_qi variable was passed into the
YSU scheme, not the flag_qc. The flag_qc variable was added to
the call. Now, both the flag_qc and flag_qi logicals are used
as arguments to the bl_ysu_run scheme. This is, conveniently,
also what the WRF group did in a separate repository.

2. The INTENT of a number of variables (znt, ust, hpbl, wspd,
all of the computed tendency arrays, wstar, and delta) were
determined based on the use in the bl_ysu_run routine. These
INTENTs were fixed in the bl_ysu_run and ysu routines. For
variables that are INTENT(OUT), remove all initializations. For
variables that are INTENT(IN), do not copy them back into the
MPAS variables.

3. Able to reproduce bit-for-bit results for 24-h simulation
on 40962 cells.

4. TBD: This version of the code should fit into WRF, but the
assumed chemistry array (qmix) needs to be optional in MPAS.
Not in the critical path.

5. The ctopo and ctopo2 arrays: WRF (both dy cores) and
MPAS include the arrays in the calling arguments. So, they do not
appear to need to be `optional`, and the `present` tests could 
be removed. Keeping them optional for eventual CESM/CAM usage.

6. For support of the CPF work, the two error arguments that
are required for the CPF-compliant routines (the error
message and the error flag) are passed through the call
chain to the bl_ysu_run routine. To verify that the arguments are 
passed correctly, a temporary print was included in atm_do_timestep. 
Each model time step printed out the following success
message based on the errflg value:
```
 Physics OK: bl_ysu_run OK
```

7. The metadata file associated with the `bl_ysu_run` scheme has been added as part
of the the repository. The `bl_ysu.meta` file is specifically set up to work with the
`bl_ysu_run` routine, not the outer `ysu` scheme.

modified:   src/core_atmosphere/mpas_atm_core.F
modified:   src/core_atmosphere/physics/mpas_atmphys_driver.F
modified:   src/core_atmosphere/physics/mpas_atmphys_driver_pbl.F
modified:   src/core_atmosphere/physics/physics_sima/bl_ysu.F

added:   src/core_atmosphere/physics/physics_sima/bl_ysu.meta

### CODE REVIEW

**Comment by davegill** [comment]
@ldfowler58 
Laura,
Don't merge this yet. I want to 
1. fix the ctopo arrays (get rid of the optional, present stuff)
2. bring in the chemistry array correctly (for WRF and MPAS)
3. test bit for bit in WRF

**Comment by davegill** [comment]
@ldfowler58 
Laura,
still do not merge, but an update:
1. still need ctopo to be fixed, no need for the optional / present things
2. waiting for a determination on how to do chem - not in our critical path, can ignore this concern
3. bit-for-bit checks with WRF (but I have to change the 0.33333335 value to 0.33333333)

**Comment by davegill** [comment]
@ldfowler58 
Laura,
OK, this is ready to review. It gives bit-for-bit results in MPAS, and the included bl_ysu.F and bl_ysu.meta are able to build the autogenerated code for CPF.

**Comment by ldfowler58** [comment]
Dave,
In subroutine bl_ysu_run, the only two arrays that uses kms and kme instead of kts and kte+1 are p2di and zq. Why do you decide to use kme?

**Comment by davegill** [comment]
@ldfowler58
Laura,
The CPF guys do not want to assume the "plus one" "minus one" vertical dimensions right now. They specifically have a vertical index for interface levels and one for layers.

**Comment by ldfowler58** [comment]
Dave, Michael, and I reviewed the pull request at yesterday's meeting. I am OK withe the merge.

**Pull request merged**
